#!/bin/sh

set -e

appdir=$(cd $(dirname "$0")/.. && pwd)
[ -f /etc/app-env ] || exec "$appdir/script/app-env" $0 $@

exec gunicorn --config="$appdir/app/config/gunicorn.py"  --pid=gunicorn.pid -b :3000 app:app
